#!/bin/bash

# This scripts generates `/all.hxml` (for Sublime Text 2/3) from other hxmls in this directory
# `dox.xml.html` is not included

rm -f all.hxml
echo -e '# For Sublime Text 2/3\n# Generated by `mk/all.hxml.sh`\n\n\n' > all.hxml
for f in `ls mk/vijka.*.hxml mk/UnitTests.*.hxml`; do
	echo -e "# $f\n" >> all.hxml
	cat $f >> all.hxml
	echo -e "\n--next\n\n\n" >> all.hxml
done
echo -e "-cmd echo Done" >> all.hxml
